kind: Service
apiVersion: v1
metadata:
  name: simple-pod-port
spec:
  selector:
    app.kubernetes.io/components: simple-pod
  type: NodePort
  ports:
    - name: simple-pod-of-the-port
      port: 3000
      nodePort: 31200 # Куда стучиться пользак
      targetPort: 80 # Куда проксировать через nodePort
