apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app.kubernetes.io/components: simple-pod
    app.kubernetes.io/name: simple-pod
spec:
  containers:
    - name: simple-pod
      image: antonlarichev/short-app
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
        requests:
          memory: "64Mi"
          cpu: "150m"
